---
version: '3'
services:
  charra-dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: fraunhofer-sit/charra-dev-env:1.5.1
    restart: unless-stopped
    container_name: charra-dev-env
    volumes:
      - ".:/home/bob/charra"
    #ports:
    #  - "127.0.0.1:8080:8080"
    #command: >
    #  /bin/bash
  charra-attester:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: fraunhofer-sit/charra:1.5.1
    restart: unless-stopped
    container_name: charra-attester
    networks:
      - arcadian-net
    ports:
      - "127.0.0.1:5683:5683"
    #command: >
    #  /home/bob/charra/bin/ra_iot_attester
    volumes:
      - ".:/home/bob/charra"
  charra-verifier:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: fraunhofer-sit/charra:1.5.1
    restart: unless-stopped
    container_name: charra-verifier
    networks:
      - arcadian-net
    #ports:
    #  - "127.0.0.1:5683:5683"
    #command: >
    #  /home/bob/charra/bin/ra_iot_verifier
    volumes:
      - ".:/home/bob/charra"
    

  attester_server:
    
    build: server/
    container_name: charra-he_server
    
    command: python3 ./server.py

    networks:
      - arcadian-net
    
    extra_hosts:
      - "localhost:host-gateway"
      - "127.0.0.1:host-gateway"
      - "0.0.0.0:host-gateway"
    
    ports:
      - 1245:1245
      #- "127.0.0.1:6900:6900"
      #- "127.0.0.1:6901:6901"
      #- "127.0.0.1:6902:6902"
      #- "127.0.0.1:6903:6903"
  
  verifier_server:
    
    build: server/
    container_name: charra-he_server
    
    command: python3 ./server.py

    networks:
      - arcadian-net
    
    extra_hosts:
      - "localhost:host-gateway"
      - "127.0.0.1:host-gateway"
      - "0.0.0.0:host-gateway"
    
    ports:
      - 1245:1245
      #- "127.0.0.1:6900:6900"
      #- "127.0.0.1:6901:6901"
      #- "127.0.0.1:6902:6902"
      #- "127.0.0.1:6903:6903"
  

networks:
  arcadian-net:
#  pub_net:
#    external: true